#
# Copyright 2011-2013 Branimir Karadzic. All rights reserved.
# License: http://www.opensource.org/licenses/BSD-2-Clause
#

rebuild:
	@make -s --no-print-directory rebuild -C 01-cubes
	@make -s --no-print-directory rebuild -C 02-metaballs
	@make -s --no-print-directory rebuild -C 03-raymarch
	@make -s --no-print-directory rebuild -C 04-mesh
	@make -s --no-print-directory rebuild -C 05-instancing
	@make -s --no-print-directory rebuild -C 06-bump
	@make -s --no-print-directory rebuild -C 07-callback
	@make -s --no-print-directory rebuild -C 08-update
	@make -s --no-print-directory rebuild -C 09-hdr
	@make -s --no-print-directory rebuild -C 10-font
	@make -s --no-print-directory rebuild -C 11-fontsdf
	@make -s --no-print-directory rebuild -C 12-lod
	@make -s --no-print-directory rebuild -C common/font
	@make -s --no-print-directory rebuild -C common/imgui
