#
# Copyright 2011-2016 Branimir Karadzic. All rights reserved.
# License: http://www.opensource.org/licenses/BSD-2-Clause
#

include ../../../scripts/shader-embeded.mk

rebuild:
	@make -s --no-print-directory clean all
