#
# Copyright 2011-2020 Branimir Karadzic. All rights reserved.
# License: https://github.com/bkaradzic/bgfx#license-bsd-2-clause
#

include ../../../../bgfx/scripts/shader-embeded.mk

rebuild:
	@make -s --no-print-directory clean all
