#
# Copyright 2011-2013 Branimir Karadzic. All rights reserved.
# License: http://www.opensource.org/licenses/BSD-2-Clause
#

include ../premake/shader-embeded.mk

rebuild:
	@make -s --no-print-directory clean all
